Update 2022
gonzalocasas/giphy-karaoke pull request #1
Opened 2022-04-13 15:07 UTC by loleg

Karaoke never goes out of style!

2022-04-13 16:40 UTC, gonzalocasas requested changes
All for updating, but before merging, let's fix the transition speed (see note below).

2022-04-13 16:40 UTC, gonzalocasas commented on index.html
> +            transition: 5s;
This transition speed doesn't look right, these things needs to transition in the 200-300ms range to feel responsive. Thjis one in particular was based based on the Material Design system (in particular the cubic bezier easing is one of the standard ones the library has/had): https://material.io/design/motion/speed.html

2022-04-19 20:25 UTC, gonzalocasas approved these changes
LGTM!

2022-04-19 20:25 UTC, merged

2022-10-11 09:25 UTC, loleg commented
What I'm actually trying to accomplish, is that the text of the search
remains visible for a couple of seconds before fading out.

> Message ID: ***@***.***
> com>
>